[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.1.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
